
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: fix-byte-order-marker
    -   id: check-docstring-first
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: check-ast
    -   id: requirements-txt-fixer
    -   id: debug-statements
    -   id: check-builtin-literals
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable

# Check for common yaml errors
-   repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
    -   id: yamllint
        args: [--no-warnings, -d, "{extends: relaxed, rules: {new-lines: disable}}"]

# Format markdown docs.
-   repo: https://github.com/executablebooks/mdformat
    # Do this before other tools "fixing" the line endings
    rev: 0.7.17
    hooks:
    -   id: mdformat
        args: [--number, --end-of-line=keep]
        additional_dependencies:
            - mdformat-toc
            - mdformat-config
            - mdformat-gfm

# Lint and Format code
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.6.6'
  hooks:
    - id: ruff
      args:
      - "--fix"  # Enable autofixes
      - "--extend-select=I"  # import sorting.
      - "--extend-select=D"  # pydocstyle
      - "--ignore=D203"  # In preference of D211
      - "--ignore=D213"  # In perference of D212
      - "--extend-select=SIM"  # flake8-simplify
      - "--extend-select=RUF"  # ruff rules.
    - id: ruff-format

# Static typehint linting.
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    -   id: mypy

# Catch typos!
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
