[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "squashpickle"
version = "0.2.0"
description = "GZIP compressed pickle serialization."
authors = [
    { name = "CreatingNull (Steve Richardson)", email="steve.public@nulltek.xyz" }
]
license = "MIT"
license-files = ["LICENSE.md"]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Topic :: System :: Archiving :: Compression",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = [
    "pickle", "compression", "gzip", "gz", "squash"
]

[tool.setuptools]
py-modules = ["squashpickle"]

[dependency-groups]
dev = [
    "pre-commit",
    "pytest",
]

[project.urls]
homepage = "https://github.com/CreatingNull/squash-pickle"
